### ISSUE TITLE
project status ?

### ISSUE THREAD

**Issue by wiryonolau** [zendframework/zend-mvc-console#22]
Is this project still deprecated ? cause zf-console it's not the answer.

**Comment by froschdesign** [comment]
> Is this project still deprecated ?

Yes: https://docs.zendframework.com/zend-mvc-console/intro/#deprecated

> cause zf-console it's not the answer.

Reasons?

**Comment by wiryonolau** [comment]
1. my app has multiple module that split to multiple vendor, each module might have console app. and have might have a lot of console route. I dont see how you can do it with zf-console. one index.php that later route to different controller is much better approach instead of multiple bin.
2. zf-console cannot create controller using factory , but service might be possible.
4. no clear docs how to inject container ( service manager ) to handler.

**Comment by wiryonolau** [comment]
most of app should be able to handle both web and cli at the same time. If I have to split  web app and console app, the config will be hell. 

what I think is zf-console seems to only focus in console app only.

**Comment by weierophinney** [comment]
Yes, zf-console only focuses on console applications, as does symfony/console (our other recommendation for console tooling).

Our experience maintaining the console tooling is that it is far too complex and has far too many edge cases where it can fail. Additionally, mixing MVC and console paradigms simply doesn't work, which tends to lead to code duplication that you would end up having with any console-specific tooling anyways.

We have found, however, that it's relatively trivial to bootstrap in a way similar to zend-mvc whereby all modules and services are initialized, giving you access to those services for purposes of your console tooling; you can, in fact, pull console-specific zf-console commands or symfony/console commands from the container and attach them to a console application runner. One approach I've seen in the wild had classes that were used to populate a symfony/console application with commands.

Because there are other and better approaches, and because handling mvc <-> console integration is so error prone, this package remains deprecated, and we have no plans to continue supporting it long-term.
